import type { Metadata } from "next";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import AntdConfig from '@/components/AntdConfig';
import ErrorBoundary from '@/components/ErrorBoundary';
import '@/app/globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <AntdRegistry>
          <AntdConfig>
            <ErrorBoundary>
              {children}
            </ErrorBoundary>
          </AntdConfig>
        </AntdRegistry>
      </body>
    </html>
  );
}
